using Loadstar.Core.Configuration;

namespace Loadstar.App;

/// <summary>
/// UI strings, per language.
///
/// <para>A plain dictionary rather than satellite <c>.resx</c> assemblies. For a single-file tray app
/// this keeps everything in one place, greppable and diffable, and avoids shipping a folder of
/// satellite DLLs beside the executable. If the string count ever outgrows one file, resx is the
/// migration — the <see cref="Get"/> lookup is the only thing callers touch.</para>
///
/// <para>A missing translation falls back to English rather than showing a key, so a partially
/// translated language is usable instead of broken.</para>
/// </summary>
internal static class Strings
{
    private static AppLanguage _language = AppLanguage.English;

    public static void Use(AppLanguage configured) => _language = AppLanguages.Resolve(configured);

    public static AppLanguage Current => _language;

    public static string Get(string key) =>
        Table.TryGetValue(_language, out var table) && table.TryGetValue(key, out var value)
            ? value
            : Table[AppLanguage.English].TryGetValue(key, out var fallback) ? fallback : key;

    private static readonly Dictionary<AppLanguage, Dictionary<string, string>> Table = new()
    {
        [AppLanguage.English] = new()
        {
            ["menu.capture"] = "Capture and ask…",
            ["menu.countdown"] = "Show boss countdown",
            ["menu.settings"] = "Settings…",
            ["menu.exit"] = "Exit",
            ["ask.title"] = "Ask about this screen",
            ["ask.placeholder"] = "Ask anything, or leave blank for a general review.  (Ctrl+Enter to send)",
            ["ask.send"] = "Ask",
            ["common.cancel"] = "Cancel",
            ["common.close"] = "Close",
            ["common.copy"] = "Copy",
            ["common.save"] = "Save",
            ["settings.title"] = "Settings",
            ["settings.general"] = "General",
            ["settings.bossTimer"] = "Boss timer",
            ["settings.windowTitle"] = "Window title",
            ["settings.refreshServers"] = "Refresh server list",
            ["settings.editHotkey"] = "Edit…",
            ["settings.buildUrl"] = "Character build URL",
            ["settings.process"] = "Game process",
            ["settings.pickWindow"] = "Pick running window…",
            ["settings.browseExe"] = "Browse for game .exe…",
            ["settings.hotkey"] = "Capture hotkey",
            ["settings.model"] = "Model",
            ["settings.apiKey"] = "API key",
            ["settings.language"] = "Language",
            ["settings.consent"] = "Screen capture enabled",
            ["settings.server"] = "Server",
            ["settings.region"] = "Region",
            ["settings.timezone"] = "Server timezone",
            ["settings.alertMinutes"] = "Alert minutes",
            ["settings.bossAlerts"] = "Notify before a boss spawns",
            ["settings.bossOverlay"] = "Show countdown overlay on screen",
            ["tray.ready"] = "Loadstar is ready",
            ["tray.pressToCapture"] = "Press {0} any time to capture the screen and ask a question.",
        },

        [AppLanguage.Russian] = new()
        {
            ["menu.capture"] = "Снимок и вопрос…",
            ["menu.countdown"] = "Показать таймер боссов",
            ["menu.settings"] = "Настройки…",
            ["menu.exit"] = "Выход",
            ["ask.title"] = "Спросить об этом экране",
            ["ask.placeholder"] = "Задайте вопрос или оставьте пустым для общего обзора.  (Ctrl+Enter — отправить)",
            ["ask.send"] = "Спросить",
            ["common.cancel"] = "Отмена",
            ["common.close"] = "Закрыть",
            ["common.copy"] = "Копировать",
            ["common.save"] = "Сохранить",
            ["settings.title"] = "Настройки",
            ["settings.buildUrl"] = "Ссылка на сборку персонажа",
            ["settings.process"] = "Процесс игры",
            ["settings.pickWindow"] = "Выбрать окно…",
            ["settings.browseExe"] = "Указать .exe игры…",
            ["settings.hotkey"] = "Горячая клавиша",
            ["settings.model"] = "Модель",
            ["settings.apiKey"] = "Ключ API",
            ["settings.language"] = "Язык",
            ["settings.consent"] = "Захват экрана включён",
            ["settings.server"] = "Сервер",
            ["settings.region"] = "Регион",
            ["settings.timezone"] = "Часовой пояс сервера",
            ["settings.alertMinutes"] = "Оповещение за (мин)",
            ["settings.bossAlerts"] = "Уведомлять перед появлением босса",
            ["settings.bossOverlay"] = "Показывать таймер поверх экрана",
            ["tray.ready"] = "Loadstar готов",
            ["tray.pressToCapture"] = "Нажмите {0}, чтобы сделать снимок экрана и задать вопрос.",
        },

        [AppLanguage.Ukrainian] = new()
        {
            ["menu.capture"] = "Знімок і запитання…",
            ["menu.countdown"] = "Показати таймер босів",
            ["menu.settings"] = "Налаштування…",
            ["menu.exit"] = "Вихід",
            ["ask.title"] = "Запитати про цей екран",
            ["ask.placeholder"] = "Поставте запитання або залиште порожнім для загального огляду.  (Ctrl+Enter — надіслати)",
            ["ask.send"] = "Запитати",
            ["common.cancel"] = "Скасувати",
            ["common.close"] = "Закрити",
            ["common.copy"] = "Копіювати",
            ["common.save"] = "Зберегти",
            ["settings.title"] = "Налаштування",
            ["settings.buildUrl"] = "Посилання на збірку персонажа",
            ["settings.process"] = "Процес гри",
            ["settings.pickWindow"] = "Обрати вікно…",
            ["settings.browseExe"] = "Вказати .exe гри…",
            ["settings.hotkey"] = "Гаряча клавіша",
            ["settings.model"] = "Модель",
            ["settings.apiKey"] = "Ключ API",
            ["settings.language"] = "Мова",
            ["settings.consent"] = "Захоплення екрана увімкнено",
            ["settings.server"] = "Сервер",
            ["settings.region"] = "Регіон",
            ["settings.timezone"] = "Часовий пояс сервера",
            ["settings.alertMinutes"] = "Сповіщення за (хв)",
            ["settings.bossAlerts"] = "Сповіщати перед появою боса",
            ["settings.bossOverlay"] = "Показувати таймер поверх екрана",
            ["tray.ready"] = "Loadstar готовий",
            ["tray.pressToCapture"] = "Натисніть {0}, щоб зробити знімок екрана та поставити запитання.",
        },

        [AppLanguage.Spanish] = new()
        {
            ["menu.capture"] = "Capturar y preguntar…",
            ["menu.countdown"] = "Mostrar cuenta atrás de jefes",
            ["menu.settings"] = "Ajustes…",
            ["menu.exit"] = "Salir",
            ["ask.title"] = "Pregunta sobre esta pantalla",
            ["ask.placeholder"] = "Pregunta lo que quieras, o déjalo vacío para un análisis general.  (Ctrl+Intro para enviar)",
            ["ask.send"] = "Preguntar",
            ["common.cancel"] = "Cancelar",
            ["common.close"] = "Cerrar",
            ["common.copy"] = "Copiar",
            ["common.save"] = "Guardar",
            ["settings.title"] = "Ajustes",
            ["settings.buildUrl"] = "URL de la build del personaje",
            ["settings.process"] = "Proceso del juego",
            ["settings.pickWindow"] = "Elegir ventana abierta…",
            ["settings.browseExe"] = "Buscar el .exe del juego…",
            ["settings.hotkey"] = "Atajo de captura",
            ["settings.model"] = "Modelo",
            ["settings.apiKey"] = "Clave API",
            ["settings.language"] = "Idioma",
            ["settings.consent"] = "Captura de pantalla activada",
            ["settings.server"] = "Servidor",
            ["settings.region"] = "Región",
            ["settings.timezone"] = "Zona horaria del servidor",
            ["settings.alertMinutes"] = "Aviso (minutos antes)",
            ["settings.bossAlerts"] = "Avisar antes de que aparezca un jefe",
            ["settings.bossOverlay"] = "Mostrar cuenta atrás en pantalla",
            ["tray.ready"] = "Loadstar está listo",
            ["tray.pressToCapture"] = "Pulsa {0} en cualquier momento para capturar la pantalla y preguntar.",
        },

        [AppLanguage.German] = new()
        {
            ["menu.capture"] = "Aufnehmen und fragen…",
            ["menu.countdown"] = "Boss-Countdown anzeigen",
            ["menu.settings"] = "Einstellungen…",
            ["menu.exit"] = "Beenden",
            ["ask.title"] = "Frage zu diesem Bildschirm",
            ["ask.placeholder"] = "Stelle eine Frage oder lass das Feld leer für eine allgemeine Einschätzung.  (Strg+Enter zum Senden)",
            ["ask.send"] = "Fragen",
            ["common.cancel"] = "Abbrechen",
            ["common.close"] = "Schließen",
            ["common.copy"] = "Kopieren",
            ["common.save"] = "Speichern",
            ["settings.title"] = "Einstellungen",
            ["settings.buildUrl"] = "URL des Charakter-Builds",
            ["settings.process"] = "Spielprozess",
            ["settings.pickWindow"] = "Laufendes Fenster wählen…",
            ["settings.browseExe"] = "Spiel-.exe suchen…",
            ["settings.hotkey"] = "Aufnahme-Tastenkürzel",
            ["settings.model"] = "Modell",
            ["settings.apiKey"] = "API-Schlüssel",
            ["settings.language"] = "Sprache",
            ["settings.consent"] = "Bildschirmaufnahme aktiviert",
            ["settings.server"] = "Server",
            ["settings.region"] = "Region",
            ["settings.timezone"] = "Zeitzone des Servers",
            ["settings.alertMinutes"] = "Vorwarnzeit (Minuten)",
            ["settings.bossAlerts"] = "Vor dem Erscheinen eines Bosses benachrichtigen",
            ["settings.bossOverlay"] = "Countdown auf dem Bildschirm anzeigen",
            ["tray.ready"] = "Loadstar ist bereit",
            ["tray.pressToCapture"] = "Drücke jederzeit {0}, um den Bildschirm aufzunehmen und zu fragen.",
        },

        [AppLanguage.French] = new()
        {
            ["menu.capture"] = "Capturer et demander…",
            ["menu.countdown"] = "Afficher le compte à rebours des boss",
            ["menu.settings"] = "Paramètres…",
            ["menu.exit"] = "Quitter",
            ["ask.title"] = "Poser une question sur cet écran",
            ["ask.placeholder"] = "Posez une question, ou laissez vide pour une analyse générale.  (Ctrl+Entrée pour envoyer)",
            ["ask.send"] = "Demander",
            ["common.cancel"] = "Annuler",
            ["common.close"] = "Fermer",
            ["common.copy"] = "Copier",
            ["common.save"] = "Enregistrer",
            ["settings.title"] = "Paramètres",
            ["settings.buildUrl"] = "URL du build de personnage",
            ["settings.process"] = "Processus du jeu",
            ["settings.pickWindow"] = "Choisir une fenêtre ouverte…",
            ["settings.browseExe"] = "Parcourir le .exe du jeu…",
            ["settings.hotkey"] = "Raccourci de capture",
            ["settings.model"] = "Modèle",
            ["settings.apiKey"] = "Clé API",
            ["settings.language"] = "Langue",
            ["settings.consent"] = "Capture d'écran activée",
            ["settings.server"] = "Serveur",
            ["settings.region"] = "Région",
            ["settings.timezone"] = "Fuseau horaire du serveur",
            ["settings.alertMinutes"] = "Alerte (minutes avant)",
            ["settings.bossAlerts"] = "Prévenir avant l'apparition d'un boss",
            ["settings.bossOverlay"] = "Afficher le compte à rebours à l'écran",
            ["tray.ready"] = "Loadstar est prêt",
            ["tray.pressToCapture"] = "Appuyez sur {0} à tout moment pour capturer l'écran et poser une question.",
        },

        [AppLanguage.Japanese] = new()
        {
            ["menu.capture"] = "キャプチャして質問…",
            ["menu.countdown"] = "ボスのカウントダウンを表示",
            ["menu.settings"] = "設定…",
            ["menu.exit"] = "終了",
            ["ask.title"] = "この画面について質問",
            ["ask.placeholder"] = "何でも質問してください。空欄なら全体的な確認を行います。（Ctrl+Enter で送信）",
            ["ask.send"] = "質問する",
            ["common.cancel"] = "キャンセル",
            ["common.close"] = "閉じる",
            ["common.copy"] = "コピー",
            ["common.save"] = "保存",
            ["settings.title"] = "設定",
            ["settings.buildUrl"] = "キャラクタービルドのURL",
            ["settings.process"] = "ゲームのプロセス",
            ["settings.pickWindow"] = "起動中のウィンドウを選択…",
            ["settings.browseExe"] = "ゲームの .exe を選択…",
            ["settings.hotkey"] = "キャプチャのホットキー",
            ["settings.model"] = "モデル",
            ["settings.apiKey"] = "APIキー",
            ["settings.language"] = "言語",
            ["settings.consent"] = "画面キャプチャを有効にする",
            ["settings.server"] = "サーバー",
            ["settings.region"] = "リージョン",
            ["settings.timezone"] = "サーバーのタイムゾーン",
            ["settings.alertMinutes"] = "通知する時間（分前）",
            ["settings.bossAlerts"] = "ボス出現前に通知する",
            ["settings.bossOverlay"] = "画面にカウントダウンを表示",
            ["tray.ready"] = "Loadstar の準備ができました",
            ["tray.pressToCapture"] = "{0} を押すと画面をキャプチャして質問できます。",
        },

        [AppLanguage.Korean] = new()
        {
            ["menu.capture"] = "캡처하고 질문하기…",
            ["menu.countdown"] = "보스 카운트다운 표시",
            ["menu.settings"] = "설정…",
            ["menu.exit"] = "종료",
            ["ask.title"] = "이 화면에 대해 질문하기",
            ["ask.placeholder"] = "무엇이든 물어보세요. 비워두면 전반적으로 검토합니다.  (Ctrl+Enter로 전송)",
            ["ask.send"] = "질문하기",
            ["common.cancel"] = "취소",
            ["common.close"] = "닫기",
            ["common.copy"] = "복사",
            ["common.save"] = "저장",
            ["settings.title"] = "설정",
            ["settings.buildUrl"] = "캐릭터 빌드 URL",
            ["settings.process"] = "게임 프로세스",
            ["settings.pickWindow"] = "실행 중인 창 선택…",
            ["settings.browseExe"] = "게임 .exe 찾아보기…",
            ["settings.hotkey"] = "캡처 단축키",
            ["settings.model"] = "모델",
            ["settings.apiKey"] = "API 키",
            ["settings.language"] = "언어",
            ["settings.consent"] = "화면 캡처 사용",
            ["settings.server"] = "서버",
            ["settings.region"] = "지역",
            ["settings.timezone"] = "서버 시간대",
            ["settings.alertMinutes"] = "알림 시간(분 전)",
            ["settings.bossAlerts"] = "보스 등장 전에 알림",
            ["settings.bossOverlay"] = "화면에 카운트다운 표시",
            ["tray.ready"] = "Loadstar 준비 완료",
            ["tray.pressToCapture"] = "언제든지 {0} 키를 눌러 화면을 캡처하고 질문하세요.",
        },

        [AppLanguage.ChineseTraditional] = new()
        {
            ["menu.capture"] = "擷取並提問…",
            ["menu.countdown"] = "顯示首領倒數計時",
            ["menu.settings"] = "設定…",
            ["menu.exit"] = "結束",
            ["ask.title"] = "詢問這個畫面",
            ["ask.placeholder"] = "有什麼想問的都可以，留空則進行整體檢視。（Ctrl+Enter 送出）",
            ["ask.send"] = "詢問",
            ["common.cancel"] = "取消",
            ["common.close"] = "關閉",
            ["common.copy"] = "複製",
            ["common.save"] = "儲存",
            ["settings.title"] = "設定",
            ["settings.buildUrl"] = "角色配裝網址",
            ["settings.process"] = "遊戲處理程序",
            ["settings.pickWindow"] = "選擇執行中的視窗…",
            ["settings.browseExe"] = "瀏覽遊戲 .exe…",
            ["settings.hotkey"] = "擷取快速鍵",
            ["settings.model"] = "模型",
            ["settings.apiKey"] = "API 金鑰",
            ["settings.language"] = "語言",
            ["settings.consent"] = "已啟用螢幕擷取",
            ["settings.server"] = "伺服器",
            ["settings.region"] = "地區",
            ["settings.timezone"] = "伺服器時區",
            ["settings.alertMinutes"] = "提前通知（分鐘）",
            ["settings.bossAlerts"] = "首領出現前通知我",
            ["settings.bossOverlay"] = "在畫面上顯示倒數計時",
            ["tray.ready"] = "Loadstar 已就緒",
            ["tray.pressToCapture"] = "隨時按下 {0} 即可擷取畫面並提問。",
        },
    };
}
