using Loadstar.Core.Configuration;

namespace Loadstar.App;

/// <summary>
/// UI strings, per language.
///
/// <para>A plain dictionary rather than satellite <c>.resx</c> assemblies. For a single-file tray app
/// this keeps everything in one place, greppable and diffable, and avoids shipping a folder of
/// satellite DLLs beside the executable. If the string count ever outgrows one file, resx is the
/// migration — the <see cref="Get"/> lookup is the only thing callers touch.</para>
///
/// <para>A missing translation falls back to English rather than showing a key, so a partially
/// translated language is usable instead of broken.</para>
/// </summary>
internal static class Strings
{
    private static AppLanguage _language = AppLanguage.English;

    public static void Use(AppLanguage configured) => _language = AppLanguages.Resolve(configured);

    public static AppLanguage Current => _language;

    public static string Get(string key) =>
        Table.TryGetValue(_language, out var table) && table.TryGetValue(key, out var value)
            ? value
            : Table[AppLanguage.English].TryGetValue(key, out var fallback) ? fallback : key;

    private static readonly Dictionary<AppLanguage, Dictionary<string, string>> Table = new()
    {
        [AppLanguage.English] = new()
        {
            ["menu.capture"] = "Capture and ask…",
            ["menu.countdown"] = "Show boss countdown",
            ["menu.settings"] = "Settings…",
            ["menu.exit"] = "Exit",
            ["ask.title"] = "Ask about this screen",
            ["ask.placeholder"] = "Ask anything, or leave blank for a general review.  (Ctrl+Enter to send)",
            ["ask.send"] = "Ask",
            ["common.cancel"] = "Cancel",
            ["common.close"] = "Close",
            ["common.copy"] = "Copy",
            ["common.save"] = "Save",
            ["settings.title"] = "Settings",
            ["settings.general"] = "General",
            ["settings.bossTimer"] = "Boss timer",
            ["settings.windowTitle"] = "Window title",
            ["settings.refreshServers"] = "Refresh server list",
            ["settings.editHotkey"] = "Edit…",
            ["settings.buildUrl"] = "Character build URL",
            ["settings.process"] = "Game process",
            ["settings.pickWindow"] = "Pick running window…",
            ["settings.browseExe"] = "Browse for game .exe…",
            ["settings.hotkey"] = "Capture hotkey",
            ["settings.model"] = "Model",
            ["settings.apiKey"] = "API key",
            ["settings.language"] = "Language",
            ["settings.consent"] = "Screen capture enabled",
            ["settings.server"] = "Server",
            ["settings.region"] = "Region",
            ["settings.timezone"] = "Server timezone",
            ["settings.alertMinutes"] = "Alert minutes",
            ["settings.bossAlerts"] = "Notify before a boss spawns",
            ["settings.bossOverlay"] = "Show countdown overlay on screen",
            ["tray.ready"] = "Loadstar is ready",
            ["tray.pressToCapture"] = "Press {0} any time to capture the screen and ask a question.",
            ["settings.language.restart"] = "The interface language has been saved. Restart Loadstar now to apply it?\n\nAnything currently on screen will be cleared. Choose No and it will apply the next time you start.",
            ["settings.language.restartFailed"] = "Loadstar could not restart itself. The new language will apply the next time you start it.",
            ["settings.hint.process"] = "Pick the running game window, or its .exe. Loadstar stores the process name - matching on window title once selected a browser tab that mentioned the game.",
            ["settings.hint.coverage"] = "Times are computed locally from a bundled schedule - no scraping, works offline. Only the Americas table is captured so far; other regions show nothing until their data is filled in.",
            ["settings.hint.alertMinutes"] = "Comma-separated, e.g. 15, 5. An alert that fires as the boss spawns is useless - travel time is the point.",
            ["settings.hint.overlay"] = "The countdown starts movable - drag it where you want, then use 'Lock countdown position' in the tray menu to make it click-through.",
            ["common.refresh"] = "Refresh",
            ["common.select"] = "Select",
            ["picker.title"] = "Pick the game window",
            ["settings.getKey"] = "Get an API key",
            ["settings.keyStored"] = "(stored - type to replace)",
            ["settings.openFailed"] = "Could not open {0} - copy it into your browser instead.",
            ["settings.billing.anthropic"] = "Per-token billing from a prepaid balance. A Claude Pro/Max subscription does not include API access.",
            ["settings.billing.openai"] = "Per-token billing from a prepaid balance. A ChatGPT Plus/Pro subscription does not include API access.",
            ["settings.billing.google"] = "Free tier available, with rate limits - the one provider that runs without a billing account. Free-tier requests may be used for training.",
            ["settings.provider"] = "AI provider",
        },

        [AppLanguage.Russian] = new()
        {
            ["menu.capture"] = "Снимок и вопрос…",
            ["menu.countdown"] = "Показать таймер боссов",
            ["menu.settings"] = "Настройки…",
            ["menu.exit"] = "Выход",
            ["ask.title"] = "Спросить об этом экране",
            ["ask.placeholder"] = "Задайте вопрос или оставьте пустым для общего обзора.  (Ctrl+Enter — отправить)",
            ["ask.send"] = "Спросить",
            ["common.cancel"] = "Отмена",
            ["common.close"] = "Закрыть",
            ["common.copy"] = "Копировать",
            ["common.save"] = "Сохранить",
            ["settings.title"] = "Настройки",
            ["settings.buildUrl"] = "Ссылка на сборку персонажа",
            ["settings.process"] = "Процесс игры",
            ["settings.pickWindow"] = "Выбрать окно…",
            ["settings.browseExe"] = "Указать .exe игры…",
            ["settings.hotkey"] = "Горячая клавиша",
            ["settings.model"] = "Модель",
            ["settings.apiKey"] = "Ключ API",
            ["settings.language"] = "Язык",
            ["settings.consent"] = "Захват экрана включён",
            ["settings.server"] = "Сервер",
            ["settings.region"] = "Регион",
            ["settings.timezone"] = "Часовой пояс сервера",
            ["settings.alertMinutes"] = "Оповещение за (мин)",
            ["settings.bossAlerts"] = "Уведомлять перед появлением босса",
            ["settings.bossOverlay"] = "Показывать таймер поверх экрана",
            ["tray.ready"] = "Loadstar готов",
            ["tray.pressToCapture"] = "Нажмите {0}, чтобы сделать снимок экрана и задать вопрос.",
            ["settings.language.restart"] = "Язык интерфейса сохранён. Перезапустить Loadstar сейчас, чтобы применить его?\n\nВсё, что сейчас на экране, будет очищено. Если выбрать «Нет», язык применится при следующем запуске.",
            ["settings.language.restartFailed"] = "Не удалось перезапустить Loadstar. Новый язык применится при следующем запуске.",
            ["settings.hint.process"] = "Выберите открытое окно игры или её .exe. Loadstar сохраняет имя процесса - поиск по заголовку окна однажды выбрал вкладку браузера, в названии которой упоминалась игра.",
            ["settings.hint.coverage"] = "Время вычисляется локально по встроенному расписанию - без обращения к сайтам, работает офлайн. Пока собрана только таблица Америки; для других регионов ничего не отображается.",
            ["settings.hint.alertMinutes"] = "Через запятую, например 15, 5. Оповещение в момент появления босса бесполезно - нужно время на дорогу.",
            ["settings.hint.overlay"] = "Таймер сначала можно перетаскивать - поставьте его куда нужно, затем выберите «Закрепить позицию таймера» в меню трея, чтобы он перестал перехватывать клики.",
            ["common.refresh"] = "Обновить",
            ["common.select"] = "Выбрать",
            ["picker.title"] = "Выбор окна игры",
            ["settings.getKey"] = "Получить ключ API",
            ["settings.keyStored"] = "(сохранён - введите новый, чтобы заменить)",
            ["settings.openFailed"] = "Не удалось открыть {0} - скопируйте адрес в браузер вручную.",
            ["settings.billing.anthropic"] = "Оплата за токены с предоплаченного баланса. Подписка Claude Pro/Max не даёт доступа к API.",
            ["settings.billing.openai"] = "Оплата за токены с предоплаченного баланса. Подписка ChatGPT Plus/Pro не даёт доступа к API.",
            ["settings.billing.google"] = "Есть бесплатный тариф с ограничениями по частоте запросов - единственный провайдер, работающий без платёжного аккаунта. Запросы бесплатного тарифа могут использоваться для обучения.",
            ["settings.general"] = "Общие",
            ["settings.bossTimer"] = "Таймер боссов",
            ["settings.windowTitle"] = "Заголовок окна",
            ["settings.refreshServers"] = "Обновить список серверов",
            ["settings.editHotkey"] = "Изменить…",
            ["settings.provider"] = "Провайдер ИИ",
        },

        [AppLanguage.Ukrainian] = new()
        {
            ["menu.capture"] = "Знімок і запитання…",
            ["menu.countdown"] = "Показати таймер босів",
            ["menu.settings"] = "Налаштування…",
            ["menu.exit"] = "Вихід",
            ["ask.title"] = "Запитати про цей екран",
            ["ask.placeholder"] = "Поставте запитання або залиште порожнім для загального огляду.  (Ctrl+Enter — надіслати)",
            ["ask.send"] = "Запитати",
            ["common.cancel"] = "Скасувати",
            ["common.close"] = "Закрити",
            ["common.copy"] = "Копіювати",
            ["common.save"] = "Зберегти",
            ["settings.title"] = "Налаштування",
            ["settings.buildUrl"] = "Посилання на збірку персонажа",
            ["settings.process"] = "Процес гри",
            ["settings.pickWindow"] = "Обрати вікно…",
            ["settings.browseExe"] = "Вказати .exe гри…",
            ["settings.hotkey"] = "Гаряча клавіша",
            ["settings.model"] = "Модель",
            ["settings.apiKey"] = "Ключ API",
            ["settings.language"] = "Мова",
            ["settings.consent"] = "Захоплення екрана увімкнено",
            ["settings.server"] = "Сервер",
            ["settings.region"] = "Регіон",
            ["settings.timezone"] = "Часовий пояс сервера",
            ["settings.alertMinutes"] = "Сповіщення за (хв)",
            ["settings.bossAlerts"] = "Сповіщати перед появою боса",
            ["settings.bossOverlay"] = "Показувати таймер поверх екрана",
            ["tray.ready"] = "Loadstar готовий",
            ["tray.pressToCapture"] = "Натисніть {0}, щоб зробити знімок екрана та поставити запитання.",
            ["settings.language.restart"] = "Мову інтерфейсу збережено. Перезапустити Loadstar зараз, щоб її застосувати?\n\nУсе, що зараз на екрані, буде очищено. Якщо вибрати «Ні», мова застосується під час наступного запуску.",
            ["settings.language.restartFailed"] = "Не вдалося перезапустити Loadstar. Нову мову буде застосовано під час наступного запуску.",
            ["settings.hint.process"] = "Виберіть відкрите вікно гри або її .exe. Loadstar зберігає назву процесу - пошук за заголовком вікна одного разу вибрав вкладку браузера, у назві якої згадувалася гра.",
            ["settings.hint.coverage"] = "Час обчислюється локально за вбудованим розписом - без звернення до сайтів, працює офлайн. Поки зібрано лише таблицю Америки; для інших регіонів нічого не показується.",
            ["settings.hint.alertMinutes"] = "Через кому, наприклад 15, 5. Оповіщення в момент появи боса безкорисне - потрібен час на дорогу.",
            ["settings.hint.overlay"] = "Таймер спочатку можна перетягувати - поставте його куди потрібно, потім виберіть «Закріпити позицію таймера» в меню трея, щоб він перестав перехоплювати кліки.",
            ["common.refresh"] = "Оновити",
            ["common.select"] = "Вибрати",
            ["picker.title"] = "Вибір вікна гри",
            ["settings.getKey"] = "Отримати ключ API",
            ["settings.keyStored"] = "(збережено - введіть новий, щоб замінити)",
            ["settings.openFailed"] = "Не вдалося відкрити {0} - скопіюйте адресу в браузер вручну.",
            ["settings.billing.anthropic"] = "Оплата за токени з передплаченого балансу. Підписка Claude Pro/Max не дає доступу до API.",
            ["settings.billing.openai"] = "Оплата за токени з передплаченого балансу. Підписка ChatGPT Plus/Pro не дає доступу до API.",
            ["settings.billing.google"] = "Є безкоштовний тариф з обмеженнями частоти запитів - єдиний провайдер, що працює без платіжного акаунта. Запити безкоштовного тарифу можуть використовуватися для навчання.",
            ["settings.general"] = "Загальні",
            ["settings.bossTimer"] = "Таймер босів",
            ["settings.windowTitle"] = "Заголовок вікна",
            ["settings.refreshServers"] = "Оновити список серверів",
            ["settings.editHotkey"] = "Змінити…",
            ["settings.provider"] = "Провайдер ШІ",
        },

        [AppLanguage.Spanish] = new()
        {
            ["menu.capture"] = "Capturar y preguntar…",
            ["menu.countdown"] = "Mostrar cuenta atrás de jefes",
            ["menu.settings"] = "Ajustes…",
            ["menu.exit"] = "Salir",
            ["ask.title"] = "Pregunta sobre esta pantalla",
            ["ask.placeholder"] = "Pregunta lo que quieras, o déjalo vacío para un análisis general.  (Ctrl+Intro para enviar)",
            ["ask.send"] = "Preguntar",
            ["common.cancel"] = "Cancelar",
            ["common.close"] = "Cerrar",
            ["common.copy"] = "Copiar",
            ["common.save"] = "Guardar",
            ["settings.title"] = "Ajustes",
            ["settings.buildUrl"] = "URL de la build del personaje",
            ["settings.process"] = "Proceso del juego",
            ["settings.pickWindow"] = "Elegir ventana abierta…",
            ["settings.browseExe"] = "Buscar el .exe del juego…",
            ["settings.hotkey"] = "Atajo de captura",
            ["settings.model"] = "Modelo",
            ["settings.apiKey"] = "Clave API",
            ["settings.language"] = "Idioma",
            ["settings.consent"] = "Captura de pantalla activada",
            ["settings.server"] = "Servidor",
            ["settings.region"] = "Región",
            ["settings.timezone"] = "Zona horaria del servidor",
            ["settings.alertMinutes"] = "Aviso (minutos antes)",
            ["settings.bossAlerts"] = "Avisar antes de que aparezca un jefe",
            ["settings.bossOverlay"] = "Mostrar cuenta atrás en pantalla",
            ["tray.ready"] = "Loadstar está listo",
            ["tray.pressToCapture"] = "Pulsa {0} en cualquier momento para capturar la pantalla y preguntar.",
            ["settings.language.restart"] = "Se ha guardado el idioma de la interfaz. ¿Reiniciar Loadstar ahora para aplicarlo?\n\nSe borrará todo lo que haya en pantalla. Si eliges No, se aplicará el próximo inicio.",
            ["settings.language.restartFailed"] = "Loadstar no pudo reiniciarse. El nuevo idioma se aplicará el próximo inicio.",
            ["settings.hint.process"] = "Elige la ventana del juego en ejecución, o su .exe. Loadstar guarda el nombre del proceso - buscar por título de ventana llegó a seleccionar una pestaña del navegador que mencionaba el juego.",
            ["settings.hint.coverage"] = "Los horarios se calculan localmente desde un calendario incluido - sin scraping, funciona sin conexión. Por ahora solo está capturada la tabla de América; otras regiones no muestran nada.",
            ["settings.hint.alertMinutes"] = "Separados por comas, p. ej. 15, 5. Un aviso que salta cuando el jefe aparece no sirve - lo importante es el tiempo de viaje.",
            ["settings.hint.overlay"] = "La cuenta atrás empieza movible - arrástrala donde quieras y luego usa 'Fijar posición de la cuenta atrás' en el menú de la bandeja para que deje de recibir clics.",
            ["common.refresh"] = "Actualizar",
            ["common.select"] = "Seleccionar",
            ["picker.title"] = "Elegir la ventana del juego",
            ["settings.getKey"] = "Obtener una clave de API",
            ["settings.keyStored"] = "(guardada - escribe para reemplazarla)",
            ["settings.openFailed"] = "No se pudo abrir {0} - cópialo en tu navegador.",
            ["settings.billing.anthropic"] = "Facturación por tokens desde un saldo prepago. Una suscripción a Claude Pro/Max no incluye acceso a la API.",
            ["settings.billing.openai"] = "Facturación por tokens desde un saldo prepago. Una suscripción a ChatGPT Plus/Pro no incluye acceso a la API.",
            ["settings.billing.google"] = "Hay un nivel gratuito con límites de uso - el único proveedor que funciona sin cuenta de facturación. Las peticiones del nivel gratuito pueden usarse para entrenamiento.",
            ["settings.general"] = "General",
            ["settings.bossTimer"] = "Temporizador de jefes",
            ["settings.windowTitle"] = "Título de la ventana",
            ["settings.refreshServers"] = "Actualizar lista de servidores",
            ["settings.editHotkey"] = "Editar…",
            ["settings.provider"] = "Proveedor de IA",
        },

        [AppLanguage.German] = new()
        {
            ["menu.capture"] = "Aufnehmen und fragen…",
            ["menu.countdown"] = "Boss-Countdown anzeigen",
            ["menu.settings"] = "Einstellungen…",
            ["menu.exit"] = "Beenden",
            ["ask.title"] = "Frage zu diesem Bildschirm",
            ["ask.placeholder"] = "Stelle eine Frage oder lass das Feld leer für eine allgemeine Einschätzung.  (Strg+Enter zum Senden)",
            ["ask.send"] = "Fragen",
            ["common.cancel"] = "Abbrechen",
            ["common.close"] = "Schließen",
            ["common.copy"] = "Kopieren",
            ["common.save"] = "Speichern",
            ["settings.title"] = "Einstellungen",
            ["settings.buildUrl"] = "URL des Charakter-Builds",
            ["settings.process"] = "Spielprozess",
            ["settings.pickWindow"] = "Laufendes Fenster wählen…",
            ["settings.browseExe"] = "Spiel-.exe suchen…",
            ["settings.hotkey"] = "Aufnahme-Tastenkürzel",
            ["settings.model"] = "Modell",
            ["settings.apiKey"] = "API-Schlüssel",
            ["settings.language"] = "Sprache",
            ["settings.consent"] = "Bildschirmaufnahme aktiviert",
            ["settings.server"] = "Server",
            ["settings.region"] = "Region",
            ["settings.timezone"] = "Zeitzone des Servers",
            ["settings.alertMinutes"] = "Vorwarnzeit (Minuten)",
            ["settings.bossAlerts"] = "Vor dem Erscheinen eines Bosses benachrichtigen",
            ["settings.bossOverlay"] = "Countdown auf dem Bildschirm anzeigen",
            ["tray.ready"] = "Loadstar ist bereit",
            ["tray.pressToCapture"] = "Drücke jederzeit {0}, um den Bildschirm aufzunehmen und zu fragen.",
            ["settings.language.restart"] = "Die Sprache der Benutzeroberfläche wurde gespeichert. Loadstar jetzt neu starten, um sie anzuwenden?\n\nAlles, was gerade angezeigt wird, wird verworfen. Bei „Nein“ gilt sie ab dem nächsten Start.",
            ["settings.language.restartFailed"] = "Loadstar konnte nicht neu gestartet werden. Die neue Sprache gilt ab dem nächsten Start.",
            ["settings.hint.process"] = "Wähle das laufende Spielfenster oder seine .exe. Loadstar speichert den Prozessnamen - die Suche über den Fenstertitel hat einmal einen Browser-Tab ausgewählt, der das Spiel erwähnte.",
            ["settings.hint.coverage"] = "Zeiten werden lokal aus einem mitgelieferten Zeitplan berechnet - kein Scraping, funktioniert offline. Bisher ist nur die Amerika-Tabelle erfasst; andere Regionen zeigen nichts an.",
            ["settings.hint.alertMinutes"] = "Mit Komma getrennt, z. B. 15, 5. Eine Warnung genau beim Spawn ist nutzlos - es geht um die Anreisezeit.",
            ["settings.hint.overlay"] = "Der Countdown ist zunächst verschiebbar - zieh ihn an die gewünschte Stelle und wähle dann 'Countdown-Position sperren' im Tray-Menü, damit er Klicks durchlässt.",
            ["common.refresh"] = "Aktualisieren",
            ["common.select"] = "Auswählen",
            ["picker.title"] = "Spielfenster auswählen",
            ["settings.getKey"] = "API-Schlüssel holen",
            ["settings.keyStored"] = "(gespeichert - zum Ersetzen tippen)",
            ["settings.openFailed"] = "{0} konnte nicht geöffnet werden - kopiere die Adresse in deinen Browser.",
            ["settings.billing.anthropic"] = "Abrechnung pro Token von einem Prepaid-Guthaben. Ein Claude-Pro/Max-Abo enthält keinen API-Zugang.",
            ["settings.billing.openai"] = "Abrechnung pro Token von einem Prepaid-Guthaben. Ein ChatGPT-Plus/Pro-Abo enthält keinen API-Zugang.",
            ["settings.billing.google"] = "Kostenlose Stufe mit Ratenbegrenzung verfügbar - der einzige Anbieter, der ohne Zahlungskonto funktioniert. Anfragen der kostenlosen Stufe können zum Training verwendet werden.",
            ["settings.general"] = "Allgemein",
            ["settings.bossTimer"] = "Boss-Timer",
            ["settings.windowTitle"] = "Fenstertitel",
            ["settings.refreshServers"] = "Serverliste aktualisieren",
            ["settings.editHotkey"] = "Bearbeiten…",
            ["settings.provider"] = "KI-Anbieter",
        },

        [AppLanguage.French] = new()
        {
            ["menu.capture"] = "Capturer et demander…",
            ["menu.countdown"] = "Afficher le compte à rebours des boss",
            ["menu.settings"] = "Paramètres…",
            ["menu.exit"] = "Quitter",
            ["ask.title"] = "Poser une question sur cet écran",
            ["ask.placeholder"] = "Posez une question, ou laissez vide pour une analyse générale.  (Ctrl+Entrée pour envoyer)",
            ["ask.send"] = "Demander",
            ["common.cancel"] = "Annuler",
            ["common.close"] = "Fermer",
            ["common.copy"] = "Copier",
            ["common.save"] = "Enregistrer",
            ["settings.title"] = "Paramètres",
            ["settings.buildUrl"] = "URL du build de personnage",
            ["settings.process"] = "Processus du jeu",
            ["settings.pickWindow"] = "Choisir une fenêtre ouverte…",
            ["settings.browseExe"] = "Parcourir le .exe du jeu…",
            ["settings.hotkey"] = "Raccourci de capture",
            ["settings.model"] = "Modèle",
            ["settings.apiKey"] = "Clé API",
            ["settings.language"] = "Langue",
            ["settings.consent"] = "Capture d'écran activée",
            ["settings.server"] = "Serveur",
            ["settings.region"] = "Région",
            ["settings.timezone"] = "Fuseau horaire du serveur",
            ["settings.alertMinutes"] = "Alerte (minutes avant)",
            ["settings.bossAlerts"] = "Prévenir avant l'apparition d'un boss",
            ["settings.bossOverlay"] = "Afficher le compte à rebours à l'écran",
            ["tray.ready"] = "Loadstar est prêt",
            ["tray.pressToCapture"] = "Appuyez sur {0} à tout moment pour capturer l'écran et poser une question.",
            ["settings.language.restart"] = "La langue de l'interface a été enregistrée. Redémarrer Loadstar maintenant pour l'appliquer ?\n\nTout ce qui est affiché sera effacé. Si vous choisissez Non, elle s'appliquera au prochain démarrage.",
            ["settings.language.restartFailed"] = "Loadstar n'a pas pu redémarrer. La nouvelle langue s'appliquera au prochain démarrage.",
            ["settings.hint.process"] = "Choisissez la fenêtre du jeu ouverte, ou son .exe. Loadstar enregistre le nom du processus - la recherche par titre de fenêtre a déjà sélectionné un onglet de navigateur mentionnant le jeu.",
            ["settings.hint.coverage"] = "Les horaires sont calculés localement à partir d'un calendrier intégré - sans scraping, fonctionne hors ligne. Seule la table Amériques est saisie pour l'instant ; les autres régions n'affichent rien.",
            ["settings.hint.alertMinutes"] = "Séparés par des virgules, par ex. 15, 5. Une alerte au moment de l'apparition ne sert à rien - c'est le temps de trajet qui compte.",
            ["settings.hint.overlay"] = "Le compte à rebours est d'abord déplaçable - placez-le où vous voulez, puis utilisez « Verrouiller la position » dans le menu de la barre d'état pour qu'il laisse passer les clics.",
            ["common.refresh"] = "Actualiser",
            ["common.select"] = "Sélectionner",
            ["picker.title"] = "Choisir la fenêtre du jeu",
            ["settings.getKey"] = "Obtenir une clé API",
            ["settings.keyStored"] = "(enregistrée - tapez pour la remplacer)",
            ["settings.openFailed"] = "Impossible d'ouvrir {0} - copiez l'adresse dans votre navigateur.",
            ["settings.billing.anthropic"] = "Facturation au token depuis un solde prépayé. Un abonnement Claude Pro/Max n'inclut pas l'accès à l'API.",
            ["settings.billing.openai"] = "Facturation au token depuis un solde prépayé. Un abonnement ChatGPT Plus/Pro n'inclut pas l'accès à l'API.",
            ["settings.billing.google"] = "Offre gratuite disponible, avec limites de débit - le seul fournisseur qui fonctionne sans compte de facturation. Les requêtes de l'offre gratuite peuvent servir à l'entraînement.",
            ["settings.general"] = "Général",
            ["settings.bossTimer"] = "Minuteur des boss",
            ["settings.windowTitle"] = "Titre de la fenêtre",
            ["settings.refreshServers"] = "Actualiser la liste des serveurs",
            ["settings.editHotkey"] = "Modifier…",
            ["settings.provider"] = "Fournisseur d'IA",
        },

        [AppLanguage.Japanese] = new()
        {
            ["menu.capture"] = "キャプチャして質問…",
            ["menu.countdown"] = "ボスのカウントダウンを表示",
            ["menu.settings"] = "設定…",
            ["menu.exit"] = "終了",
            ["ask.title"] = "この画面について質問",
            ["ask.placeholder"] = "何でも質問してください。空欄なら全体的な確認を行います。（Ctrl+Enter で送信）",
            ["ask.send"] = "質問する",
            ["common.cancel"] = "キャンセル",
            ["common.close"] = "閉じる",
            ["common.copy"] = "コピー",
            ["common.save"] = "保存",
            ["settings.title"] = "設定",
            ["settings.buildUrl"] = "キャラクタービルドのURL",
            ["settings.process"] = "ゲームのプロセス",
            ["settings.pickWindow"] = "起動中のウィンドウを選択…",
            ["settings.browseExe"] = "ゲームの .exe を選択…",
            ["settings.hotkey"] = "キャプチャのホットキー",
            ["settings.model"] = "モデル",
            ["settings.apiKey"] = "APIキー",
            ["settings.language"] = "言語",
            ["settings.consent"] = "画面キャプチャを有効にする",
            ["settings.server"] = "サーバー",
            ["settings.region"] = "リージョン",
            ["settings.timezone"] = "サーバーのタイムゾーン",
            ["settings.alertMinutes"] = "通知する時間（分前）",
            ["settings.bossAlerts"] = "ボス出現前に通知する",
            ["settings.bossOverlay"] = "画面にカウントダウンを表示",
            ["tray.ready"] = "Loadstar の準備ができました",
            ["tray.pressToCapture"] = "{0} を押すと画面をキャプチャして質問できます。",
            ["settings.language.restart"] = "インターフェースの言語を保存しました。今すぐ Loadstar を再起動して適用しますか？\n\n画面に表示されている内容は消去されます。「いいえ」を選ぶと、次回の起動時に適用されます。",
            ["settings.language.restartFailed"] = "Loadstar を再起動できませんでした。新しい言語は次回の起動時に適用されます。",
            ["settings.hint.process"] = "起動中のゲームウィンドウ、またはその .exe を選んでください。Loadstar はプロセス名を保存します。ウィンドウ名での照合では、ゲーム名を含むブラウザーのタブが選ばれたことがあります。",
            ["settings.hint.coverage"] = "時刻は同梱のスケジュールからローカルに計算されます。スクレイピングなし、オフラインでも動作します。現在はアメリカ地域の表のみ収録済みで、他地域は何も表示されません。",
            ["settings.hint.alertMinutes"] = "カンマ区切りで、例: 15, 5。ボス出現と同時の通知では意味がありません。移動時間が肝心です。",
            ["settings.hint.overlay"] = "カウントダウンは最初は移動できます。好きな位置へドラッグしたあと、トレイメニューの「カウントダウンの位置を固定」を選ぶとクリックが透過します。",
            ["common.refresh"] = "更新",
            ["common.select"] = "選択",
            ["picker.title"] = "ゲームウィンドウの選択",
            ["settings.getKey"] = "API キーを取得",
            ["settings.keyStored"] = "（保存済み - 入力すると置き換わります）",
            ["settings.openFailed"] = "{0} を開けませんでした。ブラウザーに貼り付けてください。",
            ["settings.billing.anthropic"] = "前払い残高からのトークン単位の課金です。Claude Pro/Max のサブスクリプションに API 利用は含まれません。",
            ["settings.billing.openai"] = "前払い残高からのトークン単位の課金です。ChatGPT Plus/Pro のサブスクリプションに API 利用は含まれません。",
            ["settings.billing.google"] = "レート制限付きの無料枠があり、課金アカウントなしで使える唯一のプロバイダーです。無料枠のリクエストは学習に使われる場合があります。",
            ["settings.general"] = "一般",
            ["settings.bossTimer"] = "ボスタイマー",
            ["settings.windowTitle"] = "ウィンドウ名",
            ["settings.refreshServers"] = "サーバー一覧を更新",
            ["settings.editHotkey"] = "変更…",
            ["settings.provider"] = "AI プロバイダー",
        },

        [AppLanguage.Korean] = new()
        {
            ["menu.capture"] = "캡처하고 질문하기…",
            ["menu.countdown"] = "보스 카운트다운 표시",
            ["menu.settings"] = "설정…",
            ["menu.exit"] = "종료",
            ["ask.title"] = "이 화면에 대해 질문하기",
            ["ask.placeholder"] = "무엇이든 물어보세요. 비워두면 전반적으로 검토합니다.  (Ctrl+Enter로 전송)",
            ["ask.send"] = "질문하기",
            ["common.cancel"] = "취소",
            ["common.close"] = "닫기",
            ["common.copy"] = "복사",
            ["common.save"] = "저장",
            ["settings.title"] = "설정",
            ["settings.buildUrl"] = "캐릭터 빌드 URL",
            ["settings.process"] = "게임 프로세스",
            ["settings.pickWindow"] = "실행 중인 창 선택…",
            ["settings.browseExe"] = "게임 .exe 찾아보기…",
            ["settings.hotkey"] = "캡처 단축키",
            ["settings.model"] = "모델",
            ["settings.apiKey"] = "API 키",
            ["settings.language"] = "언어",
            ["settings.consent"] = "화면 캡처 사용",
            ["settings.server"] = "서버",
            ["settings.region"] = "지역",
            ["settings.timezone"] = "서버 시간대",
            ["settings.alertMinutes"] = "알림 시간(분 전)",
            ["settings.bossAlerts"] = "보스 등장 전에 알림",
            ["settings.bossOverlay"] = "화면에 카운트다운 표시",
            ["tray.ready"] = "Loadstar 준비 완료",
            ["tray.pressToCapture"] = "언제든지 {0} 키를 눌러 화면을 캡처하고 질문하세요.",
            ["settings.language.restart"] = "인터페이스 언어를 저장했습니다. 지금 Loadstar를 다시 시작하여 적용할까요?\n\n화면에 표시된 내용은 지워집니다. '아니요'를 선택하면 다음 실행 시 적용됩니다.",
            ["settings.language.restartFailed"] = "Loadstar를 다시 시작할 수 없습니다. 새 언어는 다음 실행 시 적용됩니다.",
            ["settings.hint.process"] = "실행 중인 게임 창 또는 해당 .exe를 선택하세요. Loadstar는 프로세스 이름을 저장합니다. 창 제목으로 찾을 때 게임 이름이 포함된 브라우저 탭이 선택된 적이 있습니다.",
            ["settings.hint.coverage"] = "시간은 내장된 일정표로 로컬에서 계산됩니다. 스크래핑이 없고 오프라인에서도 동작합니다. 현재는 아메리카 지역 표만 수집되어 있으며 다른 지역은 아무것도 표시되지 않습니다.",
            ["settings.hint.alertMinutes"] = "쉼표로 구분, 예: 15, 5. 보스가 등장하는 순간의 알림은 쓸모없습니다. 이동 시간이 핵심입니다.",
            ["settings.hint.overlay"] = "카운트다운은 처음에는 옮길 수 있습니다. 원하는 위치로 끌어다 놓고 트레이 메뉴의 '카운트다운 위치 고정'을 선택하면 클릭이 통과합니다.",
            ["common.refresh"] = "새로 고침",
            ["common.select"] = "선택",
            ["picker.title"] = "게임 창 선택",
            ["settings.getKey"] = "API 키 발급받기",
            ["settings.keyStored"] = "(저장됨 - 입력하면 교체됩니다)",
            ["settings.openFailed"] = "{0}을(를) 열 수 없습니다. 브라우저에 직접 붙여넣으세요.",
            ["settings.billing.anthropic"] = "선불 잔액에서 토큰 단위로 청구됩니다. Claude Pro/Max 구독에는 API 사용이 포함되지 않습니다.",
            ["settings.billing.openai"] = "선불 잔액에서 토큰 단위로 청구됩니다. ChatGPT Plus/Pro 구독에는 API 사용이 포함되지 않습니다.",
            ["settings.billing.google"] = "사용량 제한이 있는 무료 등급이 있으며, 결제 계정 없이 쓸 수 있는 유일한 제공업체입니다. 무료 등급 요청은 학습에 사용될 수 있습니다.",
            ["settings.general"] = "일반",
            ["settings.bossTimer"] = "보스 타이머",
            ["settings.windowTitle"] = "창 제목",
            ["settings.refreshServers"] = "서버 목록 새로 고침",
            ["settings.editHotkey"] = "편집…",
            ["settings.provider"] = "AI 제공업체",
        },

        [AppLanguage.ChineseTraditional] = new()
        {
            ["menu.capture"] = "擷取並提問…",
            ["menu.countdown"] = "顯示首領倒數計時",
            ["menu.settings"] = "設定…",
            ["menu.exit"] = "結束",
            ["ask.title"] = "詢問這個畫面",
            ["ask.placeholder"] = "有什麼想問的都可以，留空則進行整體檢視。（Ctrl+Enter 送出）",
            ["ask.send"] = "詢問",
            ["common.cancel"] = "取消",
            ["common.close"] = "關閉",
            ["common.copy"] = "複製",
            ["common.save"] = "儲存",
            ["settings.title"] = "設定",
            ["settings.buildUrl"] = "角色配裝網址",
            ["settings.process"] = "遊戲處理程序",
            ["settings.pickWindow"] = "選擇執行中的視窗…",
            ["settings.browseExe"] = "瀏覽遊戲 .exe…",
            ["settings.hotkey"] = "擷取快速鍵",
            ["settings.model"] = "模型",
            ["settings.apiKey"] = "API 金鑰",
            ["settings.language"] = "語言",
            ["settings.consent"] = "已啟用螢幕擷取",
            ["settings.server"] = "伺服器",
            ["settings.region"] = "地區",
            ["settings.timezone"] = "伺服器時區",
            ["settings.alertMinutes"] = "提前通知（分鐘）",
            ["settings.bossAlerts"] = "首領出現前通知我",
            ["settings.bossOverlay"] = "在畫面上顯示倒數計時",
            ["tray.ready"] = "Loadstar 已就緒",
            ["tray.pressToCapture"] = "隨時按下 {0} 即可擷取畫面並提問。",
            ["settings.language.restart"] = "介面語言已儲存。要立即重新啟動 Loadstar 以套用嗎？\n\n畫面上顯示的內容將會清除。若選擇「否」，將於下次啟動時套用。",
            ["settings.language.restartFailed"] = "無法重新啟動 Loadstar。新語言將於下次啟動時套用。",
            ["settings.hint.process"] = "請選擇正在執行的遊戲視窗，或其 .exe。Loadstar 會儲存處理程序名稱。以視窗標題比對曾經選到標題含有遊戲名稱的瀏覽器分頁。",
            ["settings.hint.coverage"] = "時間由內建時程在本機計算，不抓取網站，離線也能運作。目前僅收錄美洲地區的表格，其他地區不會顯示任何內容。",
            ["settings.hint.alertMinutes"] = "以逗號分隔，例如 15, 5。首領出現當下才通知並無用處，重點是移動時間。",
            ["settings.hint.overlay"] = "倒數計時一開始可以拖曳，放到想要的位置後，再從系統匣選單選擇「鎖定倒數位置」，即可讓點擊穿透。",
            ["common.refresh"] = "重新整理",
            ["common.select"] = "選擇",
            ["picker.title"] = "選擇遊戲視窗",
            ["settings.getKey"] = "取得 API 金鑰",
            ["settings.keyStored"] = "（已儲存 - 輸入即可取代）",
            ["settings.openFailed"] = "無法開啟 {0}，請自行複製到瀏覽器。",
            ["settings.billing.anthropic"] = "以預付餘額按 token 計費。Claude Pro/Max 訂閱不包含 API 使用權。",
            ["settings.billing.openai"] = "以預付餘額按 token 計費。ChatGPT Plus/Pro 訂閱不包含 API 使用權。",
            ["settings.billing.google"] = "提供有速率限制的免費方案，是唯一無需付款帳戶即可使用的供應商。免費方案的請求可能被用於訓練。",
            ["settings.general"] = "一般",
            ["settings.bossTimer"] = "首領計時器",
            ["settings.windowTitle"] = "視窗標題",
            ["settings.refreshServers"] = "重新整理伺服器清單",
            ["settings.editHotkey"] = "編輯…",
            ["settings.provider"] = "AI 供應商",
        },
    };
}
