using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

using Loadstar.Core.Capture;

namespace Loadstar.Games.ThroneAndLiberty;

/// <summary>
/// The shipped signature index for everything a character sheet can hold, and the identification entry point.
///
/// <para><b>Embedded rather than downloaded.</b> Building this needs ~1,500 icons from questlog's CDN, which
/// is minutes of first-run latency and a hard runtime dependency on a third party — against a desktop app
/// where being offline is the normal state. Quantised to signed bytes the whole thing is about 800 KB inside
/// a 62 MB installer, so identification works on a fresh install, with no network, immediately.</para>
///
/// <para>Regenerated by <c>--icon-probe</c>, which writes <c>gear-index.json</c> beside the executable; that
/// file is then committed here. It has to be rebuilt when a patch adds items, and a stale index degrades
/// gracefully — an item it has never seen simply fails to match rather than matching wrongly.</para>
/// </summary>
public static class TlGearIndex
{
    private const string ResourceName = "Loadstar.Games.ThroneAndLiberty.gear-index.json";

    private static readonly Lazy<IReadOnlyList<GearCandidate>> Candidates = new(Load);

    /// <summary>Every catalogue item the index carries, with its signature. Empty if the resource is missing.</summary>
    public static IReadOnlyList<GearCandidate> All => Candidates.Value;

    /// <summary>
    /// Identifies the armour set on a capture, or null when this is not a character sheet or no set explains
    /// the tiles clearly enough to name.
    ///
    /// <para><b>Detecting the character sheet is free.</b> <see cref="EquipmentSlotLocator"/> only finds the
    /// full thirteen-slot grid on that screen, so "did we find thirteen tiles" doubles as the screen
    /// classifier — no separate heuristic, and no risk of running this over an inventory panel.</para>
    /// </summary>
    public static GearVerdict? Identify(Bgra32Image capture)
    {
        ArgumentNullException.ThrowIfNull(capture);

        if (All.Count == 0)
        {
            return null;
        }

        var located = EquipmentSlotLocator.Locate(capture);

        if (located.Count != TlEquipmentLayout.Order.Count)
        {
            return null;
        }

        var observed = new List<SlotSignature>();

        for (var i = 0; i < located.Count; i++)
        {
            var name = TlEquipmentLayout.SlotNameForIndex(i);

            // Armour only. Accessories do not come in sets spanning slots, so including them would score a
            // set on evidence it cannot supply and dilute the margin the decision rests on.
            if (name is not ("head" or "chest" or "hands" or "legs" or "feet" or "cloak"))
            {
                continue;
            }

            observed.Add(new SlotSignature(
                name,
                TlEquipmentLayout.CategoriesForIndex(i),
                IconSignature.Compute(capture, located[i].Artwork)));
        }

        return observed.Count == 0 ? null : GearSetIdentifier.Identify(observed, All);
    }

    /// <summary>
    /// The verdict as a prompt section, or null when there is nothing to say.
    ///
    /// <para>States the set, separates confirmed slots from merely assigned ones, and says outright that the
    /// piece count is unknown — because that is the error this whole mechanism exists to stop: advice
    /// asserting two set pieces where the player had four.</para>
    /// </summary>
    public static string? Describe(GearVerdict? verdict)
    {
        if (verdict is null)
        {
            return null;
        }

        var lines = new List<string>
        {
            "### Equipment identified locally from the icons (deterministic, not your reading)",
            string.Empty,
            $"The armour is the **{verdict.SetName}** set. This was decided by matching all the armour tiles "
            + $"against every set in the catalogue at once; it scored {verdict.MeanSimilarity:0.00} against "
            + $"{verdict.RunnerUpSimilarity:0.00} for the next best, so treat the SET as established.",
            string.Empty,
        };

        foreach (var slot in verdict.Slots.OrderBy(s => s.SlotName, StringComparer.Ordinal))
        {
            lines.Add(slot.ItemName is null
                ? $"- **{slot.SlotName}** — this set has no piece for that slot, so it is something else."
                : $"- **{slot.SlotName}** — {slot.ItemName}"
                  + (slot.Confident
                      ? " (confirmed: also beat every other item of its type)"
                      : " (assigned within the set; not independently confirmed)"));
        }

        lines.Add(string.Empty);
        lines.Add(
            "**How many pieces of the set are equipped is NOT known** and must not be stated or implied. "
            + "Similarity cannot separate a set member from a non-member — in testing a correct piece scored "
            + "lower than an item from a different set — so a slot marked \"assigned\" may be wrong. If a "
            + "count matters, ask the player to hover one piece and capture the tooltip, which states it.");

        return string.Join(Environment.NewLine, lines);
    }

    private static IReadOnlyList<GearCandidate> Load()
    {
        try
        {
            using var stream = typeof(TlGearIndex).Assembly.GetManifestResourceStream(ResourceName);

            if (stream is null)
            {
                return [];
            }

            var file = JsonSerializer.Deserialize<IndexFile>(stream);

            if (file?.Items is null || file.Grid != IconSignature.Grid)
            {
                // A grid mismatch means the index was built by a different version of the descriptor, so its
                // numbers are not comparable. Refusing is right; matching against them would be nonsense.
                return [];
            }

            var candidates = new List<GearCandidate>(file.Items.Count);

            foreach (var row in file.Items)
            {
                if (row.Id is null || row.Name is null || row.Category is null || row.Signature is null)
                {
                    continue;
                }

                var raw = Convert.FromBase64String(row.Signature);
                var values = new float[raw.Length];

                for (var i = 0; i < raw.Length; i++)
                {
                    values[i] = (sbyte)raw[i] / 127f;
                }

                if (values.Length != IconSignature.Grid * IconSignature.Grid * 3)
                {
                    continue;
                }

                candidates.Add(new GearCandidate(
                    row.Id,
                    row.Name,
                    row.Category,
                    row.SetKey,
                    row.SetName,
                    IconSignature.FromValues(values)));
            }

            return candidates;
        }
        catch (Exception ex) when (ex is JsonException or FormatException or ArgumentException or IOException)
        {
            // A corrupt index costs identification, not the app. Every caller treats an empty index as
            // "could not identify", which is already a supported answer.
            return [];
        }
    }

    private sealed record IndexFile(
        [property: JsonPropertyName("builtAt")] DateTimeOffset? BuiltAt,
        [property: JsonPropertyName("grid")] int Grid,
        [property: JsonPropertyName("items")] IReadOnlyList<IndexRow>? Items);

    private sealed record IndexRow(
        [property: JsonPropertyName("id")] string? Id,
        [property: JsonPropertyName("name")] string? Name,
        [property: JsonPropertyName("category")] string? Category,
        [property: JsonPropertyName("setKey")] string? SetKey,
        [property: JsonPropertyName("setName")] string? SetName,
        [property: JsonPropertyName("signature")] string? Signature);
}
